name: CI

on: 
  issues: 
    types: ["opened"]
  issue_comment:

  

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ctx: ${{ toJson(github) }}
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: printenv

