name: CI

on: 
  issues:
  

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      issue: ${{github.context.payload.issue}}
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: printenv

