name: CI

on: 
  issues:
  

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      x: ${{github.context}}
      issue: ${{github.context.issue}}
      payload: ${{github.context.issue.number}}
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: printenv

